### ISSUE TITLE
Kapitelspalte

### ISSUE THREAD

**Issue by blurare** [iterativintuitiv/myblog#3]
Breite erhöhen und evtl neues Layout?

<img width="666" alt="bildschirmfoto 2016-10-21 um 12 55 08" src="https://cloud.githubusercontent.com/assets/22979417/19596249/fc5be316-978d-11e6-891f-d168ab528d56.png">
<img width="457" alt="bildschirmfoto 2016-10-21 um 12 54 10" src="https://cloud.githubusercontent.com/assets/22979417/19596251/fc60fe32-978d-11e6-9588-4bd3202d8db6.png">
<img width="642" alt="bildschirmfoto 2016-10-11 um 18 25 23" src="https://cloud.githubusercontent.com/assets/22979417/19596250/fc5f16b2-978d-11e6-8af8-bbd656a210d1.png">

**Comment by iterativintuitiv** [comment]
Lass mal mit Version 1 gehen.
